version: "3.7"
services:
  proxy:
    build: .
    restart: always
    env_file: .env
    command: ["uvicorn", "--host", "${APP_HOST:-127.0.0.1}", "--port", "${APP_PORT}", "fastapi_auth_proxy.app:app"]
    network_mode: host
