version: "3.7"
services:
  proxy:
    build: .
    restart: always
    env_file: "${ENV:-.env}"
    command: ["uvicorn", "--host", "${FA_PROXY_APP_HOST:-127.0.0.1}", "--port", "${FA_PROXY_APP_PORT}", "fastapi_auth_proxy.app:app"]
    network_mode: host
