[tool.poetry]
name = "fastapi-auth-proxy"
version = "0.1.0"
description = ""
authors = ["Aynur Maksutov <maksutov_aynur@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
