from environs import Env

env = Env()

ACCESS_USERNAME = env.str('FA_PROXY_ACCESS_USERNAME')
ACCESS_PASSWORD = env.str('FA_PROXY_ACCESS_PASSWORD')

APP_HOST = env.str('FA_PROXY_APP_HOST')
APP_PORT = env.int('FA_PROXY_APP_PORT')

REDIRECT_URL = env.str('FA_PROXY_REDIRECT_URL')
